// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/github-electron/electron-prebuilt.d.ts
declare module 'electron-prebuilt' {
	var electron: string;
	export = electron;
}